/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_system_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        KernelInfo: {
            distro: string;
            type: string;
            version: string;
        };
        OsInfo: {
            name: string;
            version: string;
        };
        ResourceInfo: {
            cpuModel: string;
            /** Format: int64 */
            totalDisk: number;
            /** Format: int64 */
            totalMemory: number;
        };
        SystemInfo: {
            kernel: components["schemas"]["KernelInfo"];
            os: components["schemas"]["OsInfo"];
            resources: components["schemas"]["ResourceInfo"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_system_info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get device or system info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
        };
    };
}
